services:
  - type: web
    name: propertyiq-demo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: WA_PHONE_NUMBER_ID
        sync: false
      - key: WA_ACCESS_TOKEN
        sync: false
      - key: AGENT_WHATSAPP
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DB_ID
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
